---
- name: copy pki.repo to /etc/yum.repos.d
  tags:
    - pki
    - package-install
    - network
  copy:
    src=pki.repo
    dest=/etc/yum.repos.d/pki.repo

- name: install pki-server packages and dependencies
  tags:
    - pki
    - package-install
    - network
  yum: name={{ item }} state=present
  with_items:
    - dogtag-pki-server-theme
    - dogtag-pki-console-theme
    - pki-server
    - openssl
  when: package_install

- name: Open Firewall for services
  tags:
    - pki
    - firewall
  firewalld:
    service={{ item }}
    permanent=true
    state=enabled
    immediate=yes
  with_items:
    - ssh
    - ldap
    - ldaps
  when: has_firewalld.stat.exists

- name: Open Firewall for ports
  tags:
    - pki
    - firewall
  firewalld:
    port={{ item }}
    permanent=true
    state=enabled
    immediate=yes
  with_items:
    - 8080/tcp
    - 8443/tcp
  when: has_firewalld.stat.exists
