---
- name: Ensure yum-utils are available
  tags:
    - common
    - package-install
    - network
  yum: name=yum-utils state=present
  when: package_install

- name: Disable yum repos to prevent network access
  tags:
    - common
  command: yum-config-manager --disable {{ item }}
  with_items:
    - base
    - updates
  when: not enable_network
  changed_when: false

- name: Enable yum repos
  tags:
    - common
  command: yum-config-manager --enable {{ item }}
  with_items:
    - base
    - updates
  when: enable_network
  changed_when: false

- name: Auto-select fastest yum mirror
  tags:
    - common
    - package-install
    - network
  yum: name=yum-plugin-fastestmirror state=present
  when: package_install
